# Generated by Django 3.0.8 on 2020-10-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district_info',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='school_detail_info',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('load_addr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('homepage', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('highschool_type', models.CharField(max_length=20)),
                ('establishment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='school_info',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=20)),
                ('public', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=100)),
                ('load_addr', models.CharField(max_length=100)),
                ('office_code', models.IntegerField()),
                ('office_name', models.CharField(max_length=40)),
                ('support_code', models.IntegerField()),
                ('support_name', models.CharField(max_length=40)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
    ]
