# Generated by Django 3.0.8 on 2020-10-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='school_detail_info',
        ),
    ]
