# Generated by Django 3.0.8 on 2020-10-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_delete_school_detail_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_detail_info',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('load_addr', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('homepage', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('highschool_type', models.CharField(max_length=20)),
                ('establishment', models.CharField(max_length=20)),
            ],
        ),
    ]
